require("user.lazy")
require("user.plugins")

require("user.options")
require("user.keymaps")
require("user.colorscheme")
require("user.lsp")
require("user.nvim-tree")
require("user.gitsigns")
require("user.lualine")
require("user.telescope")
require("user.alpha")
